version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ["dependencies", "frontend"]
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      eslint-and-prettier:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "@typescript-eslint/*"
          - "prettier*"
      types:
        patterns:
          - "@types/*"
      tauri:
        patterns:
          - "@tauri-apps/*"

  - package-ecosystem: cargo
    directory: "/src-tauri"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ["dependencies", "rust"]
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    labels: ["dependencies", "ci"]
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
