# SPDX-License-Identifier: AGPL-3.0-or-later
name: cargo-deny

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  cargo-deny:
    name: cargo-deny
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install cargo-deny
        run: cargo install cargo-deny --locked --quiet

      - name: Run cargo-deny
        run: cargo deny --manifest-path src-tauri/Cargo.toml check --config src-tauri/deny.toml --all-features advisories bans licenses sources
